/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;


public class VistaActividad extends javax.swing.JPanel {

    /**
     * Creates new form VistaInicio
     */
    public VistaActividad() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelInicio = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaActividad = new javax.swing.JTable();
        bajaActividad = new javax.swing.JButton();
        actualizacionActividad = new javax.swing.JButton();
        nuevaActividad = new javax.swing.JButton();

        labelInicio.setFont(new java.awt.Font("Gill Sans", 0, 36)); // NOI18N
        labelInicio.setForeground(new java.awt.Color(51, 102, 255));
        labelInicio.setText("Gestión de Actividades");

        tablaActividad.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaActividad);

        bajaActividad.setText("Baja de Actividad");
        bajaActividad.setActionCommand("bajaActividad");

        actualizacionActividad.setText("Actualización de Actividad");
        actualizacionActividad.setActionCommand("actualizacionActividad");

        nuevaActividad.setText("Nueva Actividad");
        nuevaActividad.setActionCommand("nuevaActividad");
        nuevaActividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevaActividadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelInicio)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nuevaActividad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bajaActividad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(actualizacionActividad))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 874, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(labelInicio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nuevaActividad)
                    .addComponent(bajaActividad)
                    .addComponent(actualizacionActividad))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nuevaActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevaActividadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nuevaActividadActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton actualizacionActividad;
    public javax.swing.JButton bajaActividad;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelInicio;
    public javax.swing.JButton nuevaActividad;
    public javax.swing.JTable tablaActividad;
    // End of variables declaration//GEN-END:variables
}
