/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;


public class VistaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VistaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        content = new javax.swing.JPanel();
        menu = new javax.swing.JMenuBar();
        menuInicio = new javax.swing.JMenu();
        ItemInicio = new javax.swing.JMenuItem();
        menuMonitores = new javax.swing.JMenu();
        itemMonitores = new javax.swing.JMenuItem();
        menuSocios = new javax.swing.JMenu();
        itemSocios = new javax.swing.JMenuItem();
        abrirAltaSocios = new javax.swing.JMenuItem();
        abrirBajaSocios = new javax.swing.JMenuItem();
        menuActividades = new javax.swing.JMenu();
        itemActividades = new javax.swing.JMenuItem();
        menuSalir = new javax.swing.JMenu();
        ItemSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        content.setBackground(new java.awt.Color(153, 153, 153));
        content.setForeground(new java.awt.Color(204, 204, 0));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        menuInicio.setText("Inicio");

        ItemInicio.setText("Volver a la página principal");
        ItemInicio.setActionCommand("Volver");
        ItemInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemInicioActionPerformed(evt);
            }
        });
        menuInicio.add(ItemInicio);

        menu.add(menuInicio);

        menuMonitores.setText("Monitores");

        itemMonitores.setText("Gestión de Monitores");
        itemMonitores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMonitoresActionPerformed(evt);
            }
        });
        menuMonitores.add(itemMonitores);

        menu.add(menuMonitores);

        menuSocios.setText("Socios");

        itemSocios.setText("Gestión de Socios");
        itemSocios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSociosActionPerformed(evt);
            }
        });
        menuSocios.add(itemSocios);

        abrirAltaSocios.setText("Alta Socios");
        abrirAltaSocios.setActionCommand("abrirAltaSocios");
        abrirAltaSocios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirAltaSociosActionPerformed(evt);
            }
        });
        menuSocios.add(abrirAltaSocios);

        abrirBajaSocios.setText("Baja Socios");
        abrirBajaSocios.setActionCommand("abrirBajaSocios");
        abrirBajaSocios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirBajaSociosActionPerformed(evt);
            }
        });
        menuSocios.add(abrirBajaSocios);

        menu.add(menuSocios);

        menuActividades.setText("Actividades");

        itemActividades.setText("Gestión de Actividades");
        menuActividades.add(itemActividades);

        menu.add(menuActividades);

        menuSalir.setText("Salir");

        ItemSalir.setText("Salir de la aplicación");
        ItemSalir.setActionCommand("Cerrar");
        menuSalir.add(ItemSalir);

        menu.add(menuSalir);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemSociosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSociosActionPerformed
        
    }//GEN-LAST:event_itemSociosActionPerformed

    private void itemMonitoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMonitoresActionPerformed
        
    }//GEN-LAST:event_itemMonitoresActionPerformed

    private void ItemInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ItemInicioActionPerformed

    private void abrirAltaSociosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirAltaSociosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_abrirAltaSociosActionPerformed

    private void abrirBajaSociosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirBajaSociosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_abrirBajaSociosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenuItem ItemInicio;
    public javax.swing.JMenuItem ItemSalir;
    public javax.swing.JMenuItem abrirAltaSocios;
    public javax.swing.JMenuItem abrirBajaSocios;
    public javax.swing.JPanel content;
    public javax.swing.JMenuItem itemActividades;
    public javax.swing.JMenuItem itemMonitores;
    public javax.swing.JMenuItem itemSocios;
    private javax.swing.JMenuBar menu;
    private javax.swing.JMenu menuActividades;
    public javax.swing.JMenu menuInicio;
    private javax.swing.JMenu menuMonitores;
    public javax.swing.JMenu menuSalir;
    private javax.swing.JMenu menuSocios;
    // End of variables declaration//GEN-END:variables
}
